### ISSUE TITLE
As a User, I want to be able to sign in with my email and password

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#16]

**Comment by vimaguelo** [comment]
So my account is secure and nobody else can access my questions or information.

**Comment by Evowox** [comment]
**Acceptance test:**
-Once a user gets to the home page they should see the login button on the top right
-The user clicks on the log-in button: gets redirected to /signin page
-Once on that page they will see a text field to input email or username, and another text field for password
-Once sign in is pressed they will be redirected to the home page, signed in.
