### ISSUE TITLE
As a User, I want to be able to post a question

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#18]

**Comment by vimaguelo** [comment]
So that other users can see it and help me resolve it.

**Comment by Evowox** [comment]
Acceptance test:
-Once a user gets to the home page they should click on post a question button at the top: gets redirected to /postaquestion
-Once on that page they will see a text field to input Question title and another for the question itself, he will be prompted to select a tag (programming language)
-Once the button submit is clicked on: gets redirected to home and question is posted as most recent
-If no tag is selected, it will be posted without tag
-if it has no question title, the user will be prompted to input a title (Fill out this field)
-if it has no body, the user will be prompted to input a question (Fill out this field)
