### ISSUE TITLE
As a user, I want to be able to see other people's questions

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#19]

**Comment by vimaguelo** [comment]
So that I can share my knowledge and help others.

**Comment by Evowox** [comment]
Acceptance test:
-Once a user gets to the home page, the questions will be posted as such: latest at the top to last at the bottom.
-If a user clicks on a question, he will be redirected to the /anwser page with access to all the answers
-if the user hovers over View question button on some they will be prompted to select how they want their question to be sorted (Vastest/most popular/Most controversial)
