### ISSUE TITLE
As a user, I want tp be able to upvote or downvote on a question

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#47]
The system shall allow users to upvote questions and downvoting them 

Points: 3
Priority:  **Medium**
Risk:  **Low Risk, Low value**
Estimated time:  **3h**

**Comment by Evowox** [comment]
**Acceptance test:**
-Once a user gets to the home and they're signed in, they can click on the upvote and downvote buttons
-if upvote is clicked it will add one vote to the question (blue)
-if downvote is clicked it will remove one vote from the question (red)
-The total displayed will be the difference between upvotes and downvotes
