### ISSUE TITLE
As a user I want to be able to assign a tag to my question

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#49]
The System shall allow the user to add a programming language tag to his question
The System shall display this tag to other users
The System shall provide the proper Syntax highlighting for the programming language provided in the tag

Points: 3
Priority: Low
Risk: Low Risk, Low value
Estimated time: 2h

**Comment by uzairali245** [comment]
**Acceptance Testing**

- Once a user signed in and clicks post question
- He is redirected to post question page
- User can select the tag to identify what programming language this question is related to
- Once question is posted tag is visible besides it on homepage
