### ISSUE TITLE
As a user I want to be able to Choose a best Answer

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/SOEN341#64]
The system shall allow users to choose a comment as a best answer for their question

Points:2
Priority: Medium
Risk: Low Risk, High value
Estimated time: 2h

**Comment by uzairali245** [comment]
**Acceptance Test**

- Once a user is signed in and clicks on question posted by himself
- It redirects to answer page where all possible to answer to that specific question is shown
- User can click on star next to the answer thats most helpful and this would mark that answer as best one
- Now the best answer will be shown at the top in answers page
